import { HvigorNode, HvigorPlugin } from '@ohos/hvigor';
import { hapTasks } from '@ohos/hvigor-ohos-plugin';
import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import process from 'node:process';

function gitOutput(repoRoot: string, args: string[]): string {
  try {
    return execFileSync('git', ['-C', repoRoot, ...args], {
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'ignore']
    }).trim();
  } catch (_error) {
    return '';
  }
}

function generateBuildMetadata(): void {
  const repoRoot = path.resolve(process.cwd());
  const fullCommit = gitOutput(repoRoot, ['rev-parse', 'HEAD']);
  const shortCommit = fullCommit.length >= 12 ? fullCommit.substring(0, 12) : 'unknown';
  const dirty = gitOutput(repoRoot, ['status', '--porcelain']).length > 0;
  const label = `${shortCommit}${dirty ? '-dirty' : ''}`;
  const targetDirectory = path.resolve(repoRoot, 'entry', 'src', 'main', 'ets', 'generated');
  const targetFile = path.resolve(targetDirectory, 'BuildMetadata.ets');
  const source =
    '// Generated by entry/hvigorfile.ts. Do not edit or commit this file.\n' +
    `export const BUILD_GIT_COMMIT: string = '${fullCommit.length > 0 ? fullCommit : 'unknown'}';\n` +
    `export const BUILD_GIT_REVISION: string = '${shortCommit}';\n` +
    `export const BUILD_GIT_DIRTY: boolean = ${dirty};\n` +
    `export const BUILD_GIT_LABEL: string = '${label}';\n`;
  fs.mkdirSync(targetDirectory, { recursive: true });
  if (!fs.existsSync(targetFile) || fs.readFileSync(targetFile, 'utf8') !== source) {
    fs.writeFileSync(targetFile, source, { encoding: 'utf8' });
  }
}

function runCoreTests(repoRoot: string): void {
  const shell = process.platform === 'win32' ? 'powershell.exe' : 'pwsh';
  const testScript = path.resolve(repoRoot, 'scripts', 'test-core.ps1');
  console.log('PalmKeep: running core unit tests before compilation...');
  execFileSync(shell, [
    '-NoProfile',
    '-ExecutionPolicy',
    'Bypass',
    '-File',
    testScript
  ], {
    cwd: repoRoot,
    stdio: 'inherit'
  });
}

const coreTestGatePlugin: HvigorPlugin = {
  pluginId: 'palmkeep-core-test-gate',
  apply(node: HvigorNode): void {
    // test-core.ps1 starts a nested Hvigor `test` task. Do not attach the
    // assemble gate in that child process, otherwise future task-graph changes
    // could make the test runner recursively invoke itself.
    if (process.env.PALMKEEP_CORE_TEST_RUNNING === '1') {
      return;
    }
    node.registerTask({
      name: 'palmKeepCoreTest',
      postDependencies: ['assembleHap'],
      run: (): void => runCoreTests(path.resolve(process.cwd()))
    });
  }
};

generateBuildMetadata();

export default {
  system: hapTasks,
  plugins: [coreTestGatePlugin]
};
