import { hapTasks } from '@ohos/hvigor-ohos-plugin';
import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';

function gitOutput(repoRoot: string, args: string[]): string {
  try {
    return execFileSync('git', ['-C', repoRoot, ...args], {
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'ignore']
    }).trim();
  } catch (_error) {
    return '';
  }
}

function generateBuildMetadata(): void {
  const repoRoot = path.resolve(process.cwd());
  const fullCommit = gitOutput(repoRoot, ['rev-parse', 'HEAD']);
  const shortCommit = fullCommit.length >= 12 ? fullCommit.substring(0, 12) : 'unknown';
  const dirty = gitOutput(repoRoot, ['status', '--porcelain']).length > 0;
  const label = `${shortCommit}${dirty ? '-dirty' : ''}`;
  const targetDirectory = path.resolve(repoRoot, 'entry', 'src', 'main', 'ets', 'generated');
  const targetFile = path.resolve(targetDirectory, 'BuildMetadata.ets');
  const source =
    '// Generated by entry/hvigorfile.ts. Do not edit or commit this file.\n' +
    `export const BUILD_GIT_COMMIT: string = '${fullCommit.length > 0 ? fullCommit : 'unknown'}';\n` +
    `export const BUILD_GIT_REVISION: string = '${shortCommit}';\n` +
    `export const BUILD_GIT_DIRTY: boolean = ${dirty};\n` +
    `export const BUILD_GIT_LABEL: string = '${label}';\n`;
  fs.mkdirSync(targetDirectory, { recursive: true });
  if (!fs.existsSync(targetFile) || fs.readFileSync(targetFile, 'utf8') !== source) {
    fs.writeFileSync(targetFile, source, { encoding: 'utf8' });
  }
}

generateBuildMetadata();

export default {
  system: hapTasks,
  plugins: []
};
